### ISSUE TITLE
backports.functools_lru_cache 1.4 installed via conda, but not importable (cannot find module)

### ISSUE THREAD

**Issue by BenMGeo** [jaraco/backports.functools_lru_cache#10]
Hi,

I have a recent issue with this module after conda update --all. 
I cannot import matplotlib anymore.

The installation is 

...
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.4                      py27_1    conda-forge
...
matplotlib                2.1.0                    py27_0    conda-forge
...

Are there any known issues between those versions?

All the best
Ben

**Comment by jaraco** [comment]
As you can see [in the changelog](https://github.com/jaraco/backports.unittest_mock/blob/master/CHANGES.rst), 1.4 changed the packaging layout per #9 to match the namespace package layout of other backports packages.

So I suspect the issue is that conda isn't handling this form of namespace package properly.

In your Python environment, can you show the value of `sys.path`, and also do a directory listing on any `backports`-related directories where they're installed?

I'm not familiar with conda, so I'll do what I can with just Python/pypa knowledge.

**Comment by BenMGeo** [comment]
I "downgraded" to the defaults-package 27_0 instead of the forge 27_1 and it is currently working.

This is the current output:

```
>>> sys.path
['', '/home/bmueller/anaconda2/lib/python27.zip', '/home/bmueller/anaconda2/lib/python2.7', '/home/bmueller/anaconda2/lib/python2.7/plat-linux2', '/home/bmueller/anaconda2/lib/python2.7/lib-tk', '/home/bmueller/anaconda2/lib/python2.7/lib-old', '/home/bmueller/anaconda2/lib/python2.7/lib-dynload', '/home/bmueller/anaconda2/lib/python2.7/site-packages', '/home/bmueller/anaconda2/lib/python2.7/site-packages/contextlib2-0.5.5-py2.7.egg', '/home/bmueller/anaconda2/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg']

>>> backports.__file__
'/home/bmueller/anaconda2/lib/python2.7/site-packages/backports/__init__.pyc'

>>> backports.functools_lru_cache.__file__
'/home/bmueller/anaconda2/lib/python2.7/site-packages/backports/functools_lru_cache.pyc'
```

**Comment by jaraco** [comment]
Which module cannot be found? `backports` or `backports.functools_lru_cache`?

**Comment by BenMGeo** [comment]
backports can be imported, backports.functools_lru_cache cannot. (not in the shown setup, I'll re-update to 27_1 as a test by tomorrow)

**Comment by nvgoldin** [comment]
Hitting the same issue here(none-conda installation). Whats the proper way to import the package right now?

**Comment by jaraco** [comment]
The project test suite shows [how to import the package](https://github.com/jaraco/backports.functools_lru_cache/blob/master/tests/test_lru_cache.py).

As you can see from [the test results](https://travis-ci.org/jaraco/backports.functools_lru_cache), the package is successfully passing those tests.

Moreover:

```
$ python -m venv env
$ env/bin/pip install backports.functools_lru_cache
Collecting backports.functools_lru_cache
  Using cached backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.4
$ env/bin/python -c "from backports.functools_lru_cache import lru_cache; print('works!')"
works!
```

So it's working for me with a pip install. There must be some other factor that's causing problems.

**Comment by nvgoldin** [comment]
Yep, I agree. I don't hit it either on our test suite(which runs without a virtualenv), but I've already seen this error 2 times(on two different installations). Unfortunately I didn't collect the logs. Downgrading to the previous version resolved the issue on at least one of them.

**Comment by jaraco** [comment]
I'm not sure what to recommend here. I think perhaps it should be reported to conda, where experts there can potentially discover what the issue might be... and if they have a recommendation for this project (and other backports.* projects), then bring that back here.

**Comment by wilmardo** [comment]
@jaraco Could you reopen this issue since it seems to affect more people over at `crsmithdev/arrow`, see [this issue](https://github.com/crsmithdev/arrow/issues/495). 

I cannot find a difference in importing between what you refer to [above ](https://github.com/jaraco/backports.functools_lru_cache/blob/master/tests/test_lru_cache.py)and in the [`arrow/parser.py`](https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py) which throws an error.

I have provided some logging in the issue referenced above if you need more, please let me know 👍

**Comment by jaraco** [comment]
There's no bug here. I see claims that backports.functools_lru_cache 1.3 or later doesn't work, but it works for me:

```
$ cd /tmp
$ python -m virtualenv --python python2.7 env
Running virtualenv with interpreter /usr/local/opt/python@2/bin/python2.7
New python executable in /private/tmp/env/bin/python2.7
Also creating executable in /private/tmp/env/bin/python
Installing setuptools, pip, wheel...done.
$ env/bin/pip install backports.functools_lru_cache
Collecting backports.functools_lru_cache
  Using cached backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.5
$ env/bin/python -c "import backports.functools_lru_cache; print('worked!')"
worked!
```

Similarly, installing arrow, I'm unable to replicate the failure:

```
$ python -m virtualenv --python python2.7 env
Running virtualenv with interpreter /usr/local/opt/python@2/bin/python2.7
New python executable in /private/tmp/env/bin/python2.7
Also creating executable in /private/tmp/env/bin/python
Installing setuptools, pip, wheel...done.
$ env/bin/pip install arrow
Collecting arrow
  Downloading arrow-0.12.1.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 2.0MB/s
Collecting python-dateutil (from arrow)
  Using cached python_dateutil-2.7.2-py2.py3-none-any.whl
Collecting backports.functools_lru_cache>=1.2.1 (from arrow)
  Using cached backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->arrow)
  Using cached six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: arrow
  Running setup.py bdist_wheel for arrow ... done
  Stored in directory: /Users/jaraco/Library/Caches/pip/wheels/8b/f0/11/a675889f0f47d50ace5f8e1015c138c10a90e50327078710fd
Successfully built arrow
Installing collected packages: six, python-dateutil, backports.functools-lru-cache, arrow
Successfully installed arrow-0.12.1 backports.functools-lru-cache-1.5 python-dateutil-2.7.2 six-1.11.0
$ env/bin/python -c "import backports.functools_lru_cache; print('worked!')"
worked!
$ env/bin/python -c "import arrow.parser; print('worked!')"
worked!
```

For this to be a bug with this project, someone would first need to demonstrate how the issue can be replicated. I tried downgrading to pip 6. I tried installing from sdist instead of wheel.

```
$ env/bin/pip install --no-use-wheel backports.functools_lru_cache
You are using pip version 6.1.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting backports.functools-lru-cache
  Downloading backports.functools_lru_cache-1.5.tar.gz
Installing collected packages: backports.functools-lru-cache
  Running setup.py install for backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.5
$ env/bin/python -c "import arrow.parser; print('worked!')"
worked!
```

I couldn't replicate the issue. There's something unique to the environments where the error is occurring. And since I can't replicate it, I need someone in one of those environments to trace the issue.

Moreover, this ticket is about conda, which I don't think is relevant in the arrow ticket. I'll follow up in the arrow ticket instead... until there's something identified that's actionable in this project.
