### ISSUE TITLE
Backports.functools_lru_cache 1.6.5 fails to build in python2 with certain options. 

### ISSUE THREAD

**Issue by Kinglink** [jaraco/backports.functools_lru_cache#20]
Using a requirements.txt for python2, the following requirement is requested.

> pycurl --install-option="--with-nss"

This worked 15 days ago (last known good build) and fails today, as it tries to bring in setuptools>56.   On Python2, setuptools is limited to 41.1 or so. 

Having a requirements with just 'pycurl' will build correctly.  but 'pycurl --install-option="--with-nss"' fails every time.  This requirement is based on an issue with openSSL and pytest.

It is possible to get around this by adding 

>backports.functools-lru-cache==1.6.4

to the requirements.txt but it seems problematic that it's breaking functionality, and I assume there was a good reason to create 1.6.5.  Hopefully it's reasonable to request that backports not break a requirements file like this?

**Comment by tucked** [comment]
1.6.5 advertises support for py2, and a universal wheel was shipped; however, this setuptools dep precludes building with py2 (setuptools dropped py2 support in v45.0.0):
https://github.com/jaraco/backports.functools_lru_cache/blob/69d16fc2b6aa6eb198825538af5bce90efb164fc/pyproject.toml#L2

This will cause problems for any user that installs with `--no-binary :all:` or otherwise ignores the pre-built wheel.

**Comment by jaraco** [comment]
Thanks for the report. Yes, it's getting increasingly difficult to support Python 2. Looks like in f675544c36bdb0c4e8524a92e8edd8304b401d19, I may have inadvertently dropped testing for Python 2.7. Let me see if I can get that revived.

**Comment by jaraco** [comment]
Should be fixed in 1.6.6, which is likely the final release supporting Python 2.
